{% set name = "qdldl-python" %}
{% set version = "0.1.7.post5" %}
{% set pypiname = "qdldl" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypiname[0] }}/{{ pypiname }}/{{ pypiname }}-{{ version }}.tar.gz
  sha256: 0b1399e1c49b5bed5aac8fd63ef08ab708d340c37fb426fe00128bc1f36b286e
  patches:
    - patches/0001-use-Ninja-everywhere.patch
    - patches/0002-build-against-conda-forge-s-libqdldl.patch
    - patches/0003-build-qdldlamd-as-shared-lib-and-install-it.patch
    - patches/0004-Do-not-pass-CMAKE_GENERATOR-as-variable.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja
  host:
    - python
    - pip
    - setuptools
    - wheel
    # unvendored libqdldl - version has to match upstream pinned submodule
    - libqdldl {{ libqdldl }}
    - numpy {{ numpy  }}
    - pybind11
  run:
    - python
    - numpy >=1.7
    - {{ pin_compatible('numpy') }}
    - scipy >=0.13.2

test:
  requires:
    - pytest
    - pip
  imports:
    - qdldl
  source_files:     
    - tests/        
  commands:       
    - pip check
    - pytest tests

about:
  home: https://github.com/osqp/qdldl-python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python interface to the QDLDL free LDL factorization routine for quasi-definite linear systems
  description: |
    Python interface to the [QDLDL](https://github.com/osqp/qdldl) free
    LDL factorization routine for quasi-definite linear systems: `Ax = b`.
  dev_url: https://github.com/osqp/qdldl-python
  doc_url: https://github.com/osqp/qdldl-python/blob/master/README.md

extra:
  recipe-maintainers:
    - bstellato
    - gbanjac
    - h-vetinari
