{% set name = "qdldl-python" %}
{% set version = "0.1.7" %}
{% set pypiname = "qdldl" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypiname[0] }}/{{ pypiname }}/{{ pypiname }}-{{ version }}.tar.gz
  sha256: 6c86639d11e301e78af2cce885249a286f675cce96d0e6d60f5b14f859d0f10e
  patches:
    - patches/0001-use-Ninja-and-add_CMAKE_INSTALL_PREFIX.patch
    - patches/0002-build-against-external-libqdldl.patch
    - patches/0003-build-qdldlamd-as-shared-lib-and-install-it.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - patch  # [not win]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - setuptools
    - wheel
    - libqdldl {{ version }}
    - numpy {{ numpy  }}
    - pybind11 2.10.1
  run:
    - python
    - numpy >=1.7
    - {{ pin_compatible('numpy') }}
    - scipy >=0.13.2

test:
  requires:
    - pytest
    - pip
  imports:
    - qdldl
  source_files:     
    - tests/        
  commands:       
    - pip check
    - pytest tests

about:
  home: https://github.com/osqp/qdldl-python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python interface to the QDLDL free LDL factorization routine for quasi-definite linear systems
  description: |
    Python interface to the [QDLDL](https://github.com/osqp/qdldl) free
    LDL factorization routine for quasi-definite linear systems: `Ax = b`.
  dev_url: https://github.com/osqp/qdldl-python
  doc_url: https://github.com/osqp/qdldl-python/blob/master/README.md

extra:
  recipe-maintainers:
    - bstellato
    - gbanjac
    - h-vetinari
